num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
print(num1 * num2)
n1 = float(input("Digite o 1º número: "))
n2 = float(input("Digite o 2º número: "))
n3 = float(input("Digite o 3º número: "))
n4 = float(input("Digite o 4º número: "))
n5 = float(input("Digite o 5º número: "))
media = (n1 + n2 + n3 + n4 + n5) / 5
print("A média aritmética é:", media)
preco = float(input("Valor do produto: "))
print(preco * 1.08)
n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
print(n1 - n2)
peso = float(input("Peso (kg): "))
altura = float(input("Altura (m): "))
print(peso / (altura * altura))
celsius = float(input("Temperatura em °C: "))
print((celsius * 9/5) + 32)
horas = float(input("Horas trabalhadas: "))
valor = float(input("Valor da hora: "))
print(horas * valor)